Reflective Hamiltonian Monte Carlo with Leafrog steps for exponential sampling
GeomScale/volesti pull request #143
Opened 2021-03-08 10:40 UTC by TolisChal

This PR implements the Reflective Hamiltonian Monte Carlo with leapfrog integrator to sample from the exponential distribution restricted to a convex polytope.

Algorithmic details:
-- We exploit the simple form of the gradient to reduce the cost per step.
-- When the trajectory hits the boundary it is reflected.

Implementation details:
-- The sampler is implemented by a new structure.
-- The PR extends the C++ interface for exponential sampling.
-- The sampler is integrated into the R interface of volesti.
-- This implementation is more stable than the case of exact HMC for exp. sampling, when the variance is extremely small.

2021-03-08 17:10 UTC, TolisChal commented
Comment: This PR is redundant since the Hamiltonian Monte Carlo with Leapfrog integrator is implemented in https://github.com/GeomScale/volume_approximation/pull/138 . This PR shall be updated when the previous PR is merged into develop.

2021-03-09 03:21 UTC, papachristoumarios commented
The contents of this PR can be inferred from #138 . 
More specifically, you could use the `IsotropicLinearFunctor` class from `include/ode_solvers/oracle_functors.hpp` to do exponential sampling. 

For the R interface:
What can be a good addition, is creating the functor in R and giving it as an argument (rather than parsing functions from Rcpp which is rather slow; especially if you need a "famous" density) which would yield a considerable speedup. 

Thank you in advance!

2021-03-09 03:22 UTC, papachristoumarios requested changes
The contents of this PR can be inferred from #138 . 
More specifically, you could use the `IsotropicLinearFunctor` class from `include/ode_solvers/oracle_functors.hpp` to do exponential sampling. 

For the R interface:
What can be a good addition, is creating the functor in R and giving it as an argument (rather than parsing functions from Rcpp which is rather slow; especially if you need a "famous" density) which would yield a considerable speedup. 

Thank you in advance!

2023-11-01 23:52 UTC, TolisChal commented
I'm closing this PR as it is covered by https://github.com/GeomScale/volesti/pull/216 and https://github.com/GeomScale/volesti/pull/279

2023-11-01 23:52 UTC, closed without merging